### PR TITLE
Support for Angular 15

### LINKED ISSUE #153: Angular 15 incompatible peer dependency
Would be great to get an update to support angular 15 so that forced installs are no longer required.

### PR DESCRIPTION
**Pull request by Jordan-Hall**
This resolves #153 but also migrates to a standalone functionality and created provideUserIdleConfig function. Users could also use  { provide: UserIdleConfig, useValue: config } instead but having a function makes it more flexible for anything in the future

Added a @deprecated notice to the UserIdleModule so people use the function more. The module basically calls the provideUserIdleConfig  function in the forRoot

### CODE REVIEW

**Comment by Jordan-Hall** [comment]
I believe this is now fully ready to be merged in

**Comment by rednez** [comment]
@Jordan-Hall 
Hello. Thank you for your PR. But let you ask. Did you check whether these changes are compatible with previous versions of Angular (13, 14)? I can't test it now, but on a quick review, it looks like your changes will only be compatible with version 15.

**Review by IrisArvato — APPROVED** [review]

**Comment by aksdevac** [comment]
This looks like major version bump (4.0) so I think its ok to support only angular 14/15+, previous version users can still use 3.x version. standalone was introduced in v14.

**Comment by tmorano1982** [comment]
are there any updates as to when this will be merged?

**Comment by rednez** [comment]
@Jordan-Hall 
> If this doesn't get merged i'll fork it and release a version for this an actively maintain it

This has not been merged yet because you didn't answer my question. https://github.com/rednez/angular-user-idle/pull/155#issuecomment-1415377976

**Comment by Jordan-Hall** [comment]
> @Jordan-Hall
> 
> > If this doesn't get merged i'll fork it and release a version for this an actively maintain it
> 
> This has not been merged yet because you didn't answer my question. [#155 (comment)](https://github.com/rednez/angular-user-idle/pull/155#issuecomment-1415377976)
Sorry i missed that, i'll double check 13 and 14 now. However with this being a major bump does it matter as much?

**Comment by rednez** [comment]
@Jordan-Hall

**Pull request merged**
